In [1]:
import numpy as np
import pandas as pd

In [2]:
myConjointData = pd.read_csv('~/Documents/devel/dsom/7-conjoint/data/conjoint-py-v2.csv')

In [3]:
myConjointData

    Rank  P1  P2  U1  U2  D1  D2  D3
0      7   1   0   1   0   1   0   0
1      6   1   0   0   1   1   0   0
2      8   0   1   1   0   1   0   0
3      1   0   1   0   1   1   0   0
4     10   1   0   1   0   0   1   0
5      3   1   0   0   1   0   1   0
6      4   0   1   1   0   0   1   0
7      2   0   1   0   1   0   1   0
8      9   1   0   1   0   0   0   1
9     12   1   0   0   1   0   0   1
10    11   0   1   1   0   0   0   1
11     5   0   1   0   1   0   0   1

In [7]:
fullNames = {"Rank":"Rank", \
           "P1": "PhotoF1","P2": "PhotoF2", "U1": "Ux1", \
          "U2": "Ux2", "D1":"SpecialSauce1", \
           "D2":"SpecialSauce2", "D3":"SpecialSauce3"\
          }

myConjointData.rename(columns=fullNames, inplace=True)

myConjointData

,Rank,PhotoF1,PhotoF2,Ux1,Ux2,SpecialSauce1,SpecialSauce2,SpecialSauce3
0,7,1,0,1,0,1,0,0
1,6,1,0,0,1,1,0,0
2,8,0,1,1,0,1,0,0
3,1,0,1,0,1,1,0,0
4,10,1,0,1,0,0,1,0
5,3,1,0,0,1,0,1,0
6,4,0,1,1,0,0,1,0
7,2,0,1,0,1,0,1,0
8,9,1,0,1,0,0,0,1
9,12,1,0,0,1,0,0,1
10,11,0,1,1,0,0,0,1
11,5,0,1,0,1,0,0,1

In [9]:
meanRank = []
for i in myConjointData.columns[1:]:
    newmeanRank = myConjointData["Rank"].loc[myConjointData[i] == 1].mean()
    meanRank.append(newmeanRank)

    
#total Mean or, "basic utility" is used as the "zero alternative"
totalMeanRank = sum(meanRank) / len(meanRank)



partWorths = {}
for i in range(len(meanRank)):
    name = fullNames[sorted(fullNames.keys())[i]]
    partWorths[name] = meanRank[i] - totalMeanRank

In [10]:
partWorths

{'PhotoF1': -1.666666666666667,
 'PhotoF2': -1.0,
 'Rank': -1.75,
 'SpecialSauce1': 1.333333333333333,
 'SpecialSauce2': -1.333333333333333,
 'SpecialSauce3': 1.666666666666666,
 'Ux1': 2.75}

So the optimal combination for our new Social Media platform is:
* Ux Feature 1, Special Sauce Feature 3, and our Photo Feature 2

Where the runner up would be
* Ux feature 

the one issue here though is rank is making it in but ux2 is not - hmmm